# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

RUN npm install --production

# Copy the application code
COPY . .

# Expose application port
EXPOSE 3000

# Start the application
CMD ["npm", "start"]